title:            DomKM
description:      "Thoughts on science, technology, and business."
disqus_shortname: domkm
url: http://domkm.com #Comment out url when working locally to resolve base urls correctly
domain: domkm.com

# Owner/author information
owner:
  name:           Dom Kiva-Meyer
  avatar:         freestar-512px.png
  bio:
  email:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        DomKM
  facebook:
  github:         DomKM
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   http://plus.google.com/113061429105470827929

# Analytics and webmaster tools stuff goes here
google_verify:      pSpNLLs5BxOb0YLjjZPogyoCV2EbD7Fj8szYRg-Uemc
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
# links:
#   - title: Posts
#     url: /posts
#     icon: book
#   - title: Tags
#     url: /tags
#     icon: tags
#   - title: Feed
#     url: /feed.xml
#     icon: rss

# http://jekyllrb.com/docs/permalinks/
# permalink:   /posts/:categories/:year-:month-:day-:title
permalink:   /posts/:year-:month-:day-:title

# Amount of post to show on home page
# paginate: 5

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    US/Pacific
# future:      true
pygments:    true

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["README.md", "CNAME", "Gemfile", "Gemfile.lock", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]